disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Yhetti"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "yhetti.png"
secondaryLogo = "yhetti.png"

[[params.author.links]]
email = "mailto:info@bluevatech.com"

["params.author"]
image = "lil_yhetti.png"
email = "info@bluevatech.com"
headline = "More content coming soon!"
